name: yota
description: cooking timer.
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  flutter_native_splash: ^2.2.17
  shared_preferences: ^2.0.15
  skeleton_loader: ^2.0.0+4

  # annotation for models.
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.1
  format: ^1.1.1
  uuid: ^3.0.7
  collection: ^1.17.0
  timer_builder: ^2.0.0

  flutter_app_badger: ^1.5.0
  flutter_native_timezone: ^2.0.0
  timezone: ^0.8.0
  flutter_local_notifications: ^8.2.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.12.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/svg/timer_icon/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-SemiBold.ttf
          weight: 700
        - asset: fonts/Pretendard-Bold.ttf
          weight: 800
        - asset: fonts/Pretendard-ExtraBold.ttf
          weight: 900
