// ignore_for_file: constant_identifier_names

import 'package:yota/utils/service_asset.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_svg/svg.dart';

enum TimerIcon {
  etc,
  empty,
  no_01_grapes,
  no_02_melon,
  no_03_watermelon,
  no_04_tangerine,
  no_05_lemon,
  no_06_banana,
  no_07_pineapple,
  no_08_mango,
  no_09_red_apple,
  no_10_green_apple,
  no_11_pear,
  no_12_peach,
  no_13_cherries,
  no_14_strawberry,
  no_15_blueberries,
  no_16_kiwi_fruit,
  no_17_tomato,
  no_18_olive,
  no_19_coconut,
  no_20_avocado,
  no_21_eggplant,
  no_22_potato,
  no_23_carrot,
  no_24_ear_of_corn,
  no_25_hot_pepper,
  no_26_bell_pepper,
  no_27_cucumber,
  no_28_leafy_green,
  no_29_broccoli,
  no_30_garlic,
  no_31_onion,
  no_32_mushroom,
  no_33_peanuts,
  no_34_beans,
  no_35_chestnut,
  no_36_bread,
  no_37_croissant,
  no_38_baguette_bread,
  no_39_flatbread,
  no_40_pretzel,
  no_41_bagel,
  no_42_pancakes,
  no_43_waffle,
  no_44_cheese_wedge,
  no_45_meat_on_bone,
  no_46_poultry_leg,
  no_47_chickenbreast,
  no_48_cut_of_meat,
  no_49_bacon,
  no_50_hamburger,
  no_51_french_fries,
  no_52_pizza,
  no_53_hot_dog,
  no_54_sandwich,
  no_55_taco,
  no_56_burrito,
  no_57_tamale,
  no_58_stuffed_flatbread,
  no_59_falafel,
  no_60_egg,
  no_61_softboiledegg,
  no_62_hardboiledegg,
  no_63_cooking,
  no_64_shallow_pan_of_food,
  no_65_pot_of_food,
  no_66_fondue,
  no_67_bowl_with_spoon,
  no_68_green_salad,
  no_69_popcorn,
  no_70_tofu,
  no_71_spaghetti,
  no_72_fettuccine,
  no_73_penne,
  no_74_butter,
  no_75_salt,
  no_76_canned_food,
  no_77_bento_box,
  no_78_rice_cracker,
  no_79_rice_ball,
  no_80_cooked_rice,
  no_81_curry_rice,
  no_82_steaming_bowl,
  no_83_spaghetti,
  no_84_sweetpotato,
  no_85_oden,
  no_86_sushi,
  no_87_fried_shrimp,
  no_88_fish_cake_with_swirl,
  no_89_moon_cake,
  no_90_dango,
  no_91_dumpling,
  no_92_fortune_cookie,
  no_93_takeout_box,
  no_94_crab,
  no_95_lobster,
  no_96_shrimp,
  no_97_squid,
  no_98_oyster,
  no_99_soft_ice_cream,
  no_100_shaved_ice,
  no_101_ice_cream,
  no_102_doughnut,
  no_103_cookie,
  no_104_birthday_cake,
  no_105_shortcake,
  no_106_cupcake,
  no_107_pie,
  no_108_chocolate_bar,
  no_109_candy,
  no_110_lollipop,
  no_111_custard,
  no_112_honey_pot,
  no_113_baby_bottle,
  no_114_glass_of_milk,
  no_115_hot_beverage,
  no_116_teapot,
  no_117_teacup_without_handle,
  no_118_sake,
  no_119_bottle_with_popping_cork,
  no_120_wine_glass,
  no_121_cocktail_glass,
  no_122_tropical_drink,
  no_123_beer_mug,
  no_124_clinking_beer_mugs,
  no_125_clinking_glasses,
  no_126_tumbler_glass,
  no_127_pouring_liquid,
  no_128_cup_with_straw,
  no_129_bubble_tea,
  no_130_beverage_box,
  no_131_mate,
  no_132_ice,
  no_133_chopsticks,
  no_134_fork_and_knife_with_plate,
  no_135_fork_and_knife,
  no_136_spoon,
  no_137_kitchen_knife,
  no_138_jar,
  no_139_amphora,
}

extension Utils on TimerIcon {
  SvgPicture asset({
    double? width,
    double? height,
    BoxFit? fit = BoxFit.scaleDown,
  }) =>
      SvgAsset("timer_icon/$name").asset(
        width: width,
        height: height,
        fit: fit,
      );
}

extension TimerIconTransfer on String {
  TimerIcon get toTimerIcon => TimerIcon.values
      .firstWhere((e) => e.name == this, orElse: () => TimerIcon.etc);
}
